appname = travelsphere

httpport = 8080
runmode = dev
autorender = true
copyrequestbody = true
EnableDocs = true

# Session configuration
sessionon = true
sessionname = travelsphere_session
sessionprovider = memory
sessiongcmaxlifetime = 3600

# Template settings
ViewsPath = views
StaticDir = static:static

# Log settings
log.level = Debug

